### ISSUE TITLE
上書きされないメンバーのfinal定義

### ISSUE THREAD

**Issue by ghost** [swatanabe214/study_marking_201411#1]
KadaiExceptionですが
errorCodeのsetterがないならfinalで良いのではないでしょうか？
（インスタンス化時にコンストラクターにて代入され、その後変更されないため）

**Comment by swatanabe214** [comment]
修正致しました。
ご確認お願いいたします。

**Comment by ghost** [comment]
KadaiExceptionではなくerrorCodeの値が一回セットしたら変わらないの意でした。
なので

``` Java
    private final int errorCode;
```

が妥当かと思います。

Immutableっていいます。

**Comment by swatanabe214** [comment]
意図を理解できておらず、申し訳ありませんでした。
Immutableを知らなかったので、勉強します。
ありがとうございます。

**Comment by ghost** [comment]
早速の対応ありがとうございます。
