### ISSUE TITLE
整数チェック処理を見直してください

### ISSUE THREAD

**Issue by nyao-navi** [swatanabe214/study_marking_201411#3]
parseDoubleによるチェックでは小数はチェックできません。見直してください。

**Comment by nyao-navi** [comment]
確認しました。
修正そのものはOKですが、正規表現部分は定数にあたるので、定数化しましょう。

**Comment by swatanabe214** [comment]
整数チェック処理を定数化しました。

**Comment by nyao-navi** [comment]
修正が確認できましたので、クローズとします。
