### ISSUE TITLE
フィールドは定数で定義してください

### ISSUE THREAD

**Issue by nyao-navi** [swatanabe214/study_marking_201411#4]
受注ID、製品名などのフィールドは変化することはないため、定数として定義してください。

**Comment by swatanabe214** [comment]
申し訳ありません。
指摘頂いた内容を、よく考えたのですが分からなかったので、
具体的にどのあたりなのか教えていただけませんか？

**Comment by nyao-navi** [comment]
再確認しましたが、値のチェック処理で指定している位置番号に当たります。
ただし、データクラスに置き換えればこのチェック処理もなくなると思われますので、取り下げにします。
申し訳ございませんでした。
