### ISSUE TITLE
Linuxなど、フォルダの区切り文字が「\」ではないシステム上では正常に処理されない。

### ISSUE THREAD

**Issue by TakamasaSugiura** [swatanabe214/study_marking_201411#6]
プログラムソースコード内で、「\」をフォルダの区切り文字として使用しているようですが、
その影響で、Windows以外のOSで「\」をフォルダの区切り文字としないもの(Linuxなど)では、
プログラムが正常に動きません。
(なお、Windows以外のOSに関する考慮については任意であるようですので、
「Windowsだけに対応するつもりだ」という場合は、この指摘事項の対応は不要です。)

@3875eac

**Comment by swatanabe214** [comment]
とりあえずwindowsだけに対応します。
（余力があれば対応します…）
